theme: jekyll-theme-slate
title: Company of Champions
description: A community-supported repository regarding the Company of Champions <a href="https://discord.gg/vESQQvm/">Discord</a> verification of challenge runs.

