theme: jekyll-theme-slate
title: CoC Guidelines
description: A community-supported repository regarding the Company of Champions Discord server's verification of challenge runs.
[logo]: (/images/cochighres.png)