theme: jekyll-theme-slate
title: <div style="text-align:center"> Company of Champions <img src="assets/images/cochighres.png"> </div>
description: <div style="text-align:center"> A community-driven repository supporting the Company of Champions <a href="https://discord.gg/vESQQvm/">Discord's</a> verification of challenge runs.</div>
